[project]
name = "backend"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "asyncpg>=0.31.0",
    "cython>=3.2.4",
    "fastapi[standard]>=0.128.7",
    "greenlet>=3.1.0",
    "langchain>=0.3.27",
    "langchain-openai>=0.3.32",
    "langchain-text-splitters>=0.3.9",
    "python-jose[cryptography]>=3.3.0",
    "pydantic-settings>=2.10.1",
    "psycopg2-binary>=2.9.11",
    "pydantic>=2.12.5",
    "sqlalchemy>=2.0.46",
    "email-validator>=2.2.0",
    "uvicorn>=0.40.0",
    "argon2-cffi>=25.1.0",
    "pgvector>=0.4.2",
    "alembic>=1.18.4",
]
